apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo
spec:
  selector:
    matchLabels:
      app: catalogo

  template:
    metadata:
      labels:
        app: catalogo
    spec:
      containers:
        - name: catalogo
          image: vininascimento1/arquitetura-catalogo
          ports:
            - containerPort: 4001
          env:
            - name: PRODUTO_URL
              value: "http://produto-service:4000"

---

apiVersion: v1
kind: Service
metadata:
  name: catalogo-service
  labels:
    app: catalogo-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4001
  selector:
    app: catalogo