apiVersion: apps/v1
kind: Deployment
metadata:
  name: produto
spec:
  selector:
    matchLabels:
      app: produto

  template:
    metadata:
      labels:
        app: produto
    spec:
      containers:
        - name: produto
          image: vininascimento1/arquitetura-produto
          ports:
            - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: produto-service
  labels:
    app: produto-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      nodePort: 30080
  selector:
    app: produto